import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import Layout, { siteTitle } from '../components/layout';
import NavBar from '../components/Navbar';
import Date from '../components/date';
import { about, intro, skills, projects, contactLinks } from '../config/config';
import { Intro } from '../components/Intro';
import { About } from '../components/About';
import { Skills } from '../components/Skills';
import { Footer } from '../components/Footer';
import {getSortedPostsData} from '../utils/posts'

// Styles and font imports
import { Inter } from '@next/font/google'
import utilStyles from '../styles/utils.module.css';
import styles from '../styles/Home.module.css'
import { Projects } from '../components/Projects';

const inter = Inter({ subsets: ['latin'] })

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

export default function Home({allPostsData}) {
  return (
    <>
      {/* <Layout home> */}
        <div className={styles.container}>
        {/* TODO: export as header component */}
        {/* Next js component that acts as <head> tag of the page */}
        <Head>
          <title>{siteTitle}</title>
          <meta
              name="description"
              content="My portfolio "
            />
            <meta
              property="og:image"
              content={`https://og-image.vercel.app/${encodeURI(
                siteTitle,
              )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`}
            />
            <meta name="og:title" content={siteTitle} />
            <meta name="twitter:card" content="summary_large_image" />
        </Head>

        <div className={styles.header}>
          <NavBar />
        </div>
        
        {/*  Intro component */}
        <Intro 
          title={intro.title}
          desc={intro.desc}
          // image={intro.image}
          buttons={intro.buttons}
        />

        {/*  About component */}
        <About 
          title={about.title}
          desc={about.desc}
        />
        
        {/* Skills component */}
        <Skills
          title={skills.title}
          cards={skills.cards}
        />

        {/* TODO: Experience component */}
        

        {/* : Skills component */}

        {/* : Projects component */}
        <Projects 
          title={projects.title}
          cards={projects.cards}
        />
        {/* : Contact component */}
        <Footer 
          contactLinks={contactLinks}
        />
        
        
        
        {/* <div className={styles.main}> */}
        {/* Example code: Placeholder bio */}
        {/* <section className={utilStyles.headingMd}>
          <p>[Your Self Introduction]</p>
          <p>
            (This is a sample website - you’ll be building a site like this on{' '}
            <a href="https://nextjs.org/learn">our Next.js tutorial</a>.)
          </p>
        </section> */}
        
        {/* Example code:  Blog section with dynamically generated links and pages */}
        {/* <section className={`${utilStyles.headingMd} ${utilStyles.padding1px}`}>
          <h2 className={utilStyles.headingLg}>Blog</h2>
          <ul className={utilStyles.list}>
            {allPostsData.map(({ id, date, title }) => (
              <li className={utilStyles.listItem} key={id}>
                 <Link href={`/posts/${id}`}>{title}</Link>
                <br />
                <small className={utilStyles.lightText}>
                  <Date dateString={date} />
                </small>
              </li>
            ))}
          </ul>
        </section> */}
        {/* </div> */}

      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>

          <Link
            href={"/posts/first-post"}
            className={styles.card}
            // target="_blank" // opens it in a new tab
            rel='noopener noreferrer'
          >
            <h2 className={inter.className}>
              Posts here :D <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about ME.
            </p>
          </Link>
          
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
      {/* </Layout> */}
      </div>
    </>
  )
}
